/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManuscriptsRouteImport } from './routes/manuscripts'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManuscriptsIndexRouteImport } from './routes/manuscripts.index'
import { Route as SettingsLinkTypesRouteImport } from './routes/settings.link-types'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ManuscriptsManuscriptIdRouteImport } from './routes/manuscripts.$manuscriptId'
import { Route as ImportNotionRouteImport } from './routes/import.notion'
import { Route as TopicsNoteIdCanvasRouteImport } from './routes/topics.$noteId.canvas'

const ManuscriptsRoute = ManuscriptsRouteImport.update({
  id: '/manuscripts',
  path: '/manuscripts',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuscriptsIndexRoute = ManuscriptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManuscriptsRoute,
} as any)
const SettingsLinkTypesRoute = SettingsLinkTypesRouteImport.update({
  id: '/settings/link-types',
  path: '/settings/link-types',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuscriptsManuscriptIdRoute = ManuscriptsManuscriptIdRouteImport.update({
  id: '/$manuscriptId',
  path: '/$manuscriptId',
  getParentRoute: () => ManuscriptsRoute,
} as any)
const ImportNotionRoute = ImportNotionRouteImport.update({
  id: '/import/notion',
  path: '/import/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsNoteIdCanvasRoute = TopicsNoteIdCanvasRouteImport.update({
  id: '/topics/$noteId/canvas',
  path: '/topics/$noteId/canvas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/manuscripts': typeof ManuscriptsRouteWithChildren
  '/import/notion': typeof ImportNotionRoute
  '/manuscripts/$manuscriptId': typeof ManuscriptsManuscriptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
  '/manuscripts/': typeof ManuscriptsIndexRoute
  '/topics/$noteId/canvas': typeof TopicsNoteIdCanvasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/import/notion': typeof ImportNotionRoute
  '/manuscripts/$manuscriptId': typeof ManuscriptsManuscriptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
  '/manuscripts': typeof ManuscriptsIndexRoute
  '/topics/$noteId/canvas': typeof TopicsNoteIdCanvasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/manuscripts': typeof ManuscriptsRouteWithChildren
  '/import/notion': typeof ImportNotionRoute
  '/manuscripts/$manuscriptId': typeof ManuscriptsManuscriptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
  '/manuscripts/': typeof ManuscriptsIndexRoute
  '/topics/$noteId/canvas': typeof TopicsNoteIdCanvasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/inbox'
    | '/manuscripts'
    | '/import/notion'
    | '/manuscripts/$manuscriptId'
    | '/notes/$noteId'
    | '/settings/link-types'
    | '/manuscripts/'
    | '/topics/$noteId/canvas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/inbox'
    | '/import/notion'
    | '/manuscripts/$manuscriptId'
    | '/notes/$noteId'
    | '/settings/link-types'
    | '/manuscripts'
    | '/topics/$noteId/canvas'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/inbox'
    | '/manuscripts'
    | '/import/notion'
    | '/manuscripts/$manuscriptId'
    | '/notes/$noteId'
    | '/settings/link-types'
    | '/manuscripts/'
    | '/topics/$noteId/canvas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  InboxRoute: typeof InboxRoute
  ManuscriptsRoute: typeof ManuscriptsRouteWithChildren
  ImportNotionRoute: typeof ImportNotionRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  SettingsLinkTypesRoute: typeof SettingsLinkTypesRoute
  TopicsNoteIdCanvasRoute: typeof TopicsNoteIdCanvasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manuscripts': {
      id: '/manuscripts'
      path: '/manuscripts'
      fullPath: '/manuscripts'
      preLoaderRoute: typeof ManuscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuscripts/': {
      id: '/manuscripts/'
      path: '/'
      fullPath: '/manuscripts/'
      preLoaderRoute: typeof ManuscriptsIndexRouteImport
      parentRoute: typeof ManuscriptsRoute
    }
    '/settings/link-types': {
      id: '/settings/link-types'
      path: '/settings/link-types'
      fullPath: '/settings/link-types'
      preLoaderRoute: typeof SettingsLinkTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuscripts/$manuscriptId': {
      id: '/manuscripts/$manuscriptId'
      path: '/$manuscriptId'
      fullPath: '/manuscripts/$manuscriptId'
      preLoaderRoute: typeof ManuscriptsManuscriptIdRouteImport
      parentRoute: typeof ManuscriptsRoute
    }
    '/import/notion': {
      id: '/import/notion'
      path: '/import/notion'
      fullPath: '/import/notion'
      preLoaderRoute: typeof ImportNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$noteId/canvas': {
      id: '/topics/$noteId/canvas'
      path: '/topics/$noteId/canvas'
      fullPath: '/topics/$noteId/canvas'
      preLoaderRoute: typeof TopicsNoteIdCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManuscriptsRouteChildren {
  ManuscriptsManuscriptIdRoute: typeof ManuscriptsManuscriptIdRoute
  ManuscriptsIndexRoute: typeof ManuscriptsIndexRoute
}

const ManuscriptsRouteChildren: ManuscriptsRouteChildren = {
  ManuscriptsManuscriptIdRoute: ManuscriptsManuscriptIdRoute,
  ManuscriptsIndexRoute: ManuscriptsIndexRoute,
}

const ManuscriptsRouteWithChildren = ManuscriptsRoute._addFileChildren(
  ManuscriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  InboxRoute: InboxRoute,
  ManuscriptsRoute: ManuscriptsRouteWithChildren,
  ImportNotionRoute: ImportNotionRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  SettingsLinkTypesRoute: SettingsLinkTypesRoute,
  TopicsNoteIdCanvasRoute: TopicsNoteIdCanvasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
