/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsLinkTypesRouteImport } from './routes/settings.link-types'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ImportNotionRouteImport } from './routes/import.notion'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLinkTypesRoute = SettingsLinkTypesRouteImport.update({
  id: '/settings/link-types',
  path: '/settings/link-types',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportNotionRoute = ImportNotionRouteImport.update({
  id: '/import/notion',
  path: '/import/notion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/import/notion': typeof ImportNotionRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/import/notion': typeof ImportNotionRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/import/notion': typeof ImportNotionRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/link-types': typeof SettingsLinkTypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/inbox'
    | '/import/notion'
    | '/notes/$noteId'
    | '/settings/link-types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/inbox'
    | '/import/notion'
    | '/notes/$noteId'
    | '/settings/link-types'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/inbox'
    | '/import/notion'
    | '/notes/$noteId'
    | '/settings/link-types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  InboxRoute: typeof InboxRoute
  ImportNotionRoute: typeof ImportNotionRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  SettingsLinkTypesRoute: typeof SettingsLinkTypesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/link-types': {
      id: '/settings/link-types'
      path: '/settings/link-types'
      fullPath: '/settings/link-types'
      preLoaderRoute: typeof SettingsLinkTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/notion': {
      id: '/import/notion'
      path: '/import/notion'
      fullPath: '/import/notion'
      preLoaderRoute: typeof ImportNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  InboxRoute: InboxRoute,
  ImportNotionRoute: ImportNotionRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  SettingsLinkTypesRoute: SettingsLinkTypesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
